name: Run Build & Unit Tests
on:
  pull_request:
jobs:
  build:
    uses: 'flowfuse/github-actions-workflows/.github/workflows/build_node_package.yml@v0.37.0'
    with:
      node: '[
              {"version": "18", "tests": true, "lint": true},
            ]'
